version: '3.8'
services:
  forward-proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    networks:
      - web

networks:
  web:
    driver: bridge